name: playfair
description: Simple Charting Library for Sky
version: 0.0.1
author: Chromium Authors <sky-dev@googlegroups.com>
homepage: https://github.com/domokit/playfair
environment:
  sdk: '>=1.0.0 <2.0.0'
dev_dependencies:
  test: '>=0.12.0 <0.13.0'
  test_runner: '<=0.2.16'
  dart_coveralls: '<=0.3.0'
